// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdwmmfboxatwtakqalho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkd21tZmJveGF0d3Rha3FhbGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDQ3OTUsImV4cCI6MjA3MjkyMDc5NX0.9ECCkdnj_oBlcE9xF80FuZxreTJURI9lH318c7LXfDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});